#!/usr/bin/env bash
build_dir=build.dir
if [ -f ../incbuild ]; then
    bash ../incbuild
fi
mkdir -p ${build_dir}
cd ${build_dir}
cmake ..
make
re="(MINGW|CYGWIN)"
if [[ $(uname) =~ $re ]]; then
    make install/strip
else
    sudo make install/strip
fi
cd ..
