#!/usr/bin/env bash

# version
open_jtalk_ver=1.10
hts_engine_api_ver=1.10

# folder name
open_jtalk=open_jtalk-${open_jtalk_ver}
hts_engine_api=hts_engine_API-${hts_engine_api_ver}

#cd portaudio
#./configure
#make
#make install
#cd ..

cd ${hts_engine_api}
./configure
make
re="(MINGW|CYGWIN)"
if [[ $(uname) =~ $re ]]; then
make install
else
sudo make install
fi
cd ..

cd ${open_jtalk}
./configure
make
if [[ $(uname) =~ $re ]]; then
make install
else
sudo make install
fi
cd ..
