#!/usr/bin/env bash

# command line option
# $1: i686 | x86_64 :: target architecture

build_dir=build.dir
re="(MINGW|CYGWIN)"
if [[ $(uname) =~ $re ]]; then
	bash build_portaudio_mingw $1
fi
if [ -f ../incbuild ]; then
    bash ../incbuild
fi
mkdir -p ${build_dir}
cd ${build_dir}
if [[ $(uname) =~ $re ]]; then
    rm -r *
fi
if [ ! "$1" == "" ] ; then
    param=-Dtarget_arch=$1
fi
cmake .. $param
make
if [[ $(uname) =~ $re ]]; then
    make install/strip
else
    sudo make install
fi
cd ..
