#!/usr/bin/env bash

# command line option
# $1: i686 | x86_64 :: target architecture

# arch
if [[ $(uname) =~ "MINGW" ]]; then
    export AR="ar"
    export RANLIB="ranlib"
    export CC="gcc"
    export CXX="g++"
    host=""
    target=""
    prefix=/usr/local
elif [[ $(uname) =~ "CYGWIN" ]]; then
	if [ "$1" == "" ] ; then
		arch=$(uname -m)
	else
		arch=$1
	fi
    arch=$arch-w64-mingw32
    export AR="$arch-ar"
    export RANLIB="$arch-ranlib"
    export CC="$arch-gcc"
    export CXX="$arch-g++"
    host="--host=$arch"
    target="--target=$arch"
    prefix=/usr/$arch
fi

re="(MINGW|CYGWIN)"
if [[ $(uname) =~ $re ]]; then
    cd portaudio
    chmod +x configure
    ./configure $host $target --prefix=$prefix
    make clean
    make
    make install
    cd ..
else
    cd portaudio
    chmod +x configure
    ./configure
    make clean
    make
    sudo make install
    cd ..
fi
